language: node_js
node_js:
  - "8"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
cache:
  directories:
    - "node_modules"
  yarn: true
sudo: false
after_success:
  - npm run test
deploy:
- provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  script: yarn run lerna:publish
  skip_cleanup: true
  on:
    node: 8
    tags: true
    repo: unadlib/tees
    all_branches: true
after_deploy:
- "echo 'Successful deployment!'"
